project:
  type: book
  output-dir: _site

engines: ['julia']
julia:
  project: "."

book:
  title: "WildfireData.jl"
  search:
    location: sidebar
    keyboard-shortcut:
      - "/"
  navbar:
    logo: assets/logo.svg
    logo-href: https://rallypoint1.com
    right:
      - icon: star
        href: https://github.com/RallypointOne/WildfireData.jl/stargazers
        text: "Star"
        target: _blank
      - icon: github
        href: https://github.com/RallypointOne/WildfireData.jl
        target: _blank
  chapters:
    - part: "Docs"
      chapters:
        - index.qmd
        - getting-started.qmd
        - modules/wfigs.qmd
        - modules/irwin.qmd
        - modules/fpa-fod.qmd
        - modules/mtbs.qmd
        - modules/firms.qmd
        - modules/landfire.qmd
        - modules/feds.qmd
        - modules/cwfis.qmd
        - modules/hms.qmd
        - modules/gwis.qmd
        - modules/egp.qmd
        - modules/rxcadre.qmd
    - part: "API"
      chapters:
        - pages/api.qmd
    - part: "Resources"
      chapters:
        - pages/coverage.qmd

  page-footer:
    center: "Built on __BUILD_DATE__"

language:
  search-text-placeholder: "Search  (/)"

format:
  html:
    css: assets/styles.css
    number-sections: false
    link-external-newwindow: true
    theme:
      - flatly
      - assets/theme.scss
    include-after-body:
      - file: assets/_version-selector.html
